name    'ramiel-owncloud'
version '0.1.0'
source 'https://github.com/ramiel/puppet-owncloud'
author 'Fabrizio "Ramiel" Ruggeri'
license 'Apache License, Version 2.0'
summary 'Owncloud install module'
description 'Make sure owncloud is configured and installed correctly on different environments'
project_page 'https://github.com/ramiel/puppet-owncloud'
dependency 'puppetlabs/stdlib', '>=0.1.6'
dependency 'jfryman/nginx', '>=0.0.6'
dependency 'jproyo/archive', '>=0.0.4'
dependency 'example42/php', '>=2.0.18'
